apiVersion: v1
kind: Secret
metadata:
  name: backend-secrets
  namespace: default
type: Opaque
stringData:
  # MongoDB
  MONGODB_URI: "mongodb+srv://abubakarmukhtar2002:007007007@cluster0.f11eg.mongodb.net"

  # JWT
  JWT_SECRET: "abubakarmukhtar2002"

  # Cloudinary
  CLOUDINARY_URL: "cloudinary://442835364174619:M-Jb6O0SkrIfXhnzgS-1CHK5wvc@djnezrmpu"
  CLOUDINARY_CLOUD_NAME: "djnezrmpu"
  CLOUDINARY_API_KEY: "442835364174619"
  CLOUDINARY_API_SECRET: "M-Jb6O0SkrIfXhnzgS-1CHK5wvc"

  # Email
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  EMAIL_USER: "crook00271@gmail.com"
  EMAIL_PASSWORD: "nvsysqfeunkhwxtx"
  EMAIL_FROM: "no-reply@saboyouthfoundation.org"

  # Paystack
  PAYSTACK_SECRET_KEY: "sk_test_63e1f88d889cd31da6a147c05c762a11d3122f50"
  PAYSTACK_PUBLIC_KEY: "pk_test_e0bf58a02d0bf8c7b15a05fd698542ddf63ed257"

  # Admin
  ADMIN_EMAIL: "admin@saboyouthfoundation.org"
  ADMIN_PASSWORD: "Qwerty123"

  # Sentry
  SENTRY_DSN: "https://2c5ffc967c7cd626582e23f49ad9b90f@o4508708700553216.ingest.us.sentry.io/4510861689421824"
